[project]
name = "lutherbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vincent Ferrara", email = "vferrara@umich.edu" }
]
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "discord-py>=2.3.0",
    "python-dotenv>=1.2.4",
]

[project.scripts]
lutherbot = "lutherbot:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
